title: Disclose AE Project Type Addon
description: Add-On to categorize AE docs by project type.
type: object
documents:
  - selected
  - query
properties:
  run_name:
    title: Run name to show in DocumentCloud's interface
    default: test
    type: string
  project:
    title: Project to target
    type: string
  time_limit:
    title: Time limit for Add-On runs (in minutes)
    type: integer
    default: 45
  dry_run:
    title: Dry run (no document will be processed)
    type: boolean
    default: true
required:
  - project
categories: 
  - bulk
  - ai
version: 2

eventOptions:
  name: run_name
  events:
    - hourly
    - daily
    - weekly